### ISSUE TITLE
Convert todo to a github issue

### ISSUE THREAD

**Issue by maxbeizer** [mrtazz/vim-plan#12]
@mrtazz what do you think of this idea:

1. Add a todo to a daily
2. Run a command that creates an issue on GitHub (to a configured repo)
3. Replace the todo text with a link to the issue with the todo as the title

So 
```
- [ ] my todo
```

Becomes
```
- [ ] [my todo](https://github.com/myorg/myrepo/issues/1)
```

I'm thinking maybe it would rely on the gh cli being installed.

Maybe this makes more sense as a plug-in instead of being in the vim-plan core?

**Comment by mrtazz** [comment]
> Maybe this makes more sense as a plug-in instead of being in the vim-plan core?

yea I agree. I think this makes more sense as its own plugin as it could be useful outside of `vim-plan` potentially. In my mind this is similar to https://github.com/jkramer/vim-checkbox which I'm using to quickly toggle checkbox states but don't really want to replicate the functionality inside of `vim-plan` even though it's super useful. I had initially started on [integrating some of this](https://github.com/mrtazz/vim-plan/blob/250fcb967914e5e5fd60f0fb5176fe76bcdc397c/plugin/plan.vim#L11-L12) but ended up never really using that functionality. So I might remove it again at some point.

**Comment by maxbeizer** [comment]
Cool. makes sense. 💖
